### PR TITLE
Add rbvmomi dependency

### PR DESCRIPTION
**Pull request by rishijavia**
Matching BKR [commit](https://github.com/puppetlabs/beaker/pull/1407/commits/9f8b9422c487c986b0cd78c592afe3a63a22b8e6)

[Build URL](https://jenkins-qe.delivery.puppetlabs.net/job/qe_gem_acceptance/39/)

### CODE REVIEW

**Comment by rishijavia** [comment]
@puppetlabs-jenkins test this please

**Comment by ericwilliamson** [comment]
Ok to test

**Comment by kevpl** [comment]
@puppetlabs-jenkins retest this please

**Comment by rishijavia** [comment]
@puppetlabs-jenkins retest this please

**Pull request merged**
